// ==========================================================================
// 📖 课文与字词矩阵数据（按词组单位：全拼音与双语翻译·支持自动分段） - data.js
// ==========================================================================

const lessonTitle = "心田上的百合花开";

const lessonData = [
    // --- 第1段 ---
    ["在一个", "zài yí gè", "In a", "Di dalam sebuah"],
    ["偏僻遥远的", "piān pì yáo yuǎn de", "remote and distant", "terpencil dan jauh"],
    ["山谷里，", "shān gǔ lǐ", "in the valley", "di dalam lembah"],
    ["有一个", "yǒu yí gè", "there is a", "terdapat sebuah"],
    ["高达数千尺的", "gāo dá shù qiān chǐ de", "thousands of feet high", "setinggi ribuan kaki"],
    ["断崖。", "duàn yá", "cliff", "tebing"],
    ["不知道", "bù zhī dào", "don't know", "tidak tahu"],
    ["什么时候，", "shén me shí hou", "when", "bilakah"],
    ["断崖边上", "duàn yá biān shàng", "on the edge of the cliff", "di tepi tebing"],
    ["长出了一株", "zhǎng chū le yì zhū", "grew a", "tumbuh sepohon"],
    ["小小的", "xiǎo xiǎo de", "small", "kecil"],
    ["百合。", "bǎi hé", "lily", "bunga lili."],
    ["\n", "", "", ""],

    // --- 第2段 ---
    ["百合", "bǎi hé", "lily", "bunga lili"],
    ["刚刚", "gāng gāng", "just", "baru sahaja"],
    ["诞生的时候，", "dàn shēng de shí hou", "when born", "semasa dilahirkan"],
    ["长得", "zhǎng de", "grew / looked", "tumbuh / kelihatan"],
    ["和杂草", "hé zá cǎo", "with weeds", "dengan rumpai"],
    ["一模一样。", "yì mú yí yàng", "exactly the same", "sama sebiji / serupa"],
    ["但是，", "dàn shì", "but", "namun"],
    ["它心里", "tā xīn lǐ", "it in heart", "ia dalam hati"],
    ["知道", "zhī dào", "knew", "tahu"],
    ["自己", "zì jǐ", "itself", "dirinya sendiri"],
    ["不是", "bú shì", "is not", "bukan"],
    ["一株杂草。", "yì zhū zá cǎo", "a weed", "sepohon rumpai."],
    ["它的", "tā de", "its", "ia punya"],
    ["内心深处，", "nèi xīn shēn chù", "deep inside", "dalam lubuk hati"],
    ["有一个", "yǒu yí gè", "has a", "mempunyai sebuah"],
    ["内在的", "nèi zài de", "inner", "dalaman"],
    ["纯洁的", "chún jié de", "pure", "suci"],
    ["念头：", "niàn tou", "thought", "niat:"],
    ["“我是一株", "wǒ shì yì zhū", "I am a", "Saya adalah sepohon"],
    ["百合，", "bǎi hé", "lily", "bunga lili"],
    ["不是", "bú shì", "is not", "bukan"],
    ["一株野草。", "yì zhū yě cǎo", "a wild grass", "sepohon rumput liar."],
    ["惟一能", "wéi yī néng", "the only way to", "satu-satunya cara untuk"],
    ["证明", "zhèng míng", "prove", "membuktikan"],
    ["我是百合的", "wǒ shì bǎi hé de", "I am lily", "saya adalah bunga lili"],
    ["方法，", "fāng fǎ", "method", "cara"],
    ["就是", "jiù shì", "is just", "adalah"],
    ["开出", "kāi chū", "bloom", "mengeluarkan"],
    ["美丽的花朵。”", "měi lì de huā duǒ", "beautiful flowers", "bunga yang cantik."],
    ["\n", "", "", ""],

    // --- 第3段 ---
    ["有了", "yǒu le", "having", "setelah mempunyai"],
    ["这个", "zhè gè", "this", "niat... ini"],
    ["念头，", "niàn tou", "thought", "niat"],
    ["百合", "bǎi hé", "lily", "bunga lili"],
    ["努力地", "nǔ lì dì", "diligently", "dengan gigih"],
    ["吸收", "xī shōu", "absorb", "menyerap"],
    ["水分和", "shuǐ fèn hé", "water and", "air dan"],
    ["阳光，", "yáng guāng", "sunlight", "cahaya matahari"],
    ["深深地", "shēn shēn dì", "deeply", "secara mendalam"],
    ["扎根，", "zhā gēn", "take root", "berakar"],
    ["直直地", "zhí zhí dì", "straight", "dengan lurus"],
    ["挺着胸膛。", "tǐng zhe xiōng táng", "sticking out chest", "membusungkan dada."],
    ["\n", "", "", ""],

    // --- 第4段 ---
    ["小草们", "xiǎo cǎo men", "weeds", "rumpai-rumpai"],
    ["都嘲笑它：", "dōu cháo xiào tā", "all mocked it", "semuanya mengejek ia:"],
    ["“你别", "nǐ bié", "you don't", "jangan kamu"],
    ["做梦了，", "zuò mèng le", "dreaming", "bermimpi"],
    ["这儿", "zhè r", "here", "di sini"],
    ["根本", "gēn běn", "at all", "sama sekali"],
    ["没有", "méi yǒu", "not have", "tidak ada"],
    ["百合花。”", "bǎi hé huā", "lily", "bunga lili."],
    ["\n", "", "", ""],

    // --- 第5段 ---
    ["百合花", "bǎi hé huā", "lily", "bunga lili"],
    ["不理会它们，", "bù lǐ huì tā men", "ignored them", "tidak mempedulikan mereka"],
    ["它静静地", "tā jìng jìng dì", "it quietly", "ia dengan senyap"],
    ["吸收", "xī shōu", "absorb", "menyerap"],
    ["水分和", "shuǐ fèn hé", "water and", "air dan"],
    ["阳光，", "yáng guāng", "sunlight", "cahaya matahari"],
    ["深深地", "shēn shēn dì", "deeply", "secara mendalam"],
    ["扎根，", "zhā gēn", "take root", "berakar"],
    ["直直地", "zhí zhí dì", "straight", "dengan lurus"],
    ["挺着胸膛。", "tǐng zhe xiōng táng", "sticking out chest", "membusungkan dada."],
    ["\n", "", "", ""],

    // --- 第6段 ---
    ["百合花", "bǎi hé huā", "lily", "bunga lili"],
    ["花蕾", "huā lěi", "flower bud", "kuntum bunga"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["结出了", "jié chū le", "produced", "mengeluarkan"],
    ["第一个", "dì yí gè", "the first", "yang pertama"],
    ["花苞。", "huā bāo", "flower bud", "kuntum bunga."],
    ["它依然", "tā yī rán", "it still", "ia masih tetap"],
    ["努力地", "nǔ lì dì", "diligently", "dengan gigih"],
    ["吸收", "xī shōu", "absorb", "menyerap"],
    ["水分和", "shuǐ fèn hé", "water and", "air dan"],
    ["阳光，", "yáng guāng", "sunlight", "cahaya matahari"],
    ["深深地", "shēn shēn dì", "deeply", "secara mendalam"],
    ["扎根，", "zhā gēn", "take root", "berakar"],
    ["直直地", "zhí zhí dì", "straight", "dengan lurus"],
    ["挺着胸膛。", "tǐng zhe xiōng táng", "sticking out chest", "membusungkan dada."],
    ["\n", "", "", ""],

    // --- 第7段 ---
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["有一天，", "yǒu yì tiān", "one day", "pada suatu hari"],
    ["百合花", "bǎi hé huā", "lily", "bunga lili"],
    ["开出了", "kāi chū le", "bloomed", "mengeluarkan"],
    ["第一朵", "dì yí duǒ", "the first", "kuntum yang pertama"],
    ["花。", "huā", "flower", "bunga."],
    ["\n", "", "", ""],

    // --- 第8段 ---
    ["它那", "tā nà", "its that", "ia punya... itu"],
    ["洁白如雪的", "jié bái rú xuě de", "snow-white", "yang putih bersih bagai salji"],
    ["花瓣上，", "huā bàn shàng", "on petals", "di atas kelopak bunga"],
    ["沾着", "zhān zhe", "stained with", "melekat dengan"],
    ["晶莹的", "jīng yíng de", "sparkling", "yang jernih berkilauan"],
    ["露水，", "lù shuǐ", "dew", "embun"],
    ["随风摇曳，", "suí fēng yáo yè", "swaying in the wind", "bergoyang mengikut angin"],
    ["显得", "xiǎn de", "appeared", "kelihatan"],
    ["格外美丽，", "gé wài měi lì", "extraordinarily beautiful", "sangat cantik"],
    ["格外耀眼。", "gé wài yào yǎn", "extraordinarily dazzling", "sangat bersinar."],
    ["百合花", "bǎi hé huā", "lily", "bunga lili"],
    ["一朵一朵地", "yì duǒ yì duǒ dì", "one by one", "setangkai demi setangkai"],
    ["开着，", "kāi zhe", "blooming", "sedang berbunga"],
    ["最后竟", "zuì hòu jìng", "finally unexpectedly", "akhirnya rupa-rupanya"],
    ["开满了一整座", "kāi mǎn le yì zhěng zuò", "bloomed full of an entire", "berbunga penuh seluruh"],
    ["断崖。", "duàn yá", "cliff", "tebing."],
    ["\n", "", "", ""],

    // --- 第9段 ---
    ["若干年后，", "ruò gān nián hòu", "several years later", "beberapa tahun kemudian"],
    ["远近的人们", "yuǎn jìn de rén men", "people from far and near", "orang ramai dari jauh dan dekat"],
    ["慕名而来，", "mù míng ér lái", "came attracted by the fame", "datang kerana kemasyhuran"],
    ["欣赏这", "xīn shǎng zhè", "admire this", "menghargai... ini"],
    ["断崖上的", "duàn yá shàng de", "on the cliff", "di atas tebing punya"],
    ["百合。", "bǎi hé", "lily", "bunga lili."],
    ["人们", "rén men", "people", "orang ramai"],
    ["赞叹", "zàn tàn", "admire / praise", "memuji"],
    ["风景的美丽，", "fēng jǐng de měi lì", "beauty of scenery", "keindahan pemandangan"],
    ["感叹", "gǎn tàn", "sigh with emotion", "mengeluh dengan rasa kagum"],
    ["这儿", "zhè r", "here", "di sini"],
    ["百合花的", "bǎi hé huā de", "lily's", "bunga lili punya"],
    ["纯洁。", "chún jié", "purity", "kesucian."],
    ["\n", "", "", ""],

    // --- 第10段 ---
    ["这时，", "zhè shí", "at this time", "pada waktu ini"],
    ["人们甚至", "rén men shèn zhì", "people even", "orang ramai malah"],
    ["还会说：", "hái huì shuō", "will even say", "akan berkata:"],
    ["“这儿有一株", "zhè r yǒu yì zhū", "here is a", "di sini ada sepohon"],
    ["美丽的", "měi lì de", "beautiful", "yang cantik"],
    ["百合呢。”", "bǎi hé ne", "lily", "bunga lili."],
    ["\n", "", "", ""],

    // --- 第11段 ---
    ["即使", "jí shǐ", "even if", "walaupun"],
    ["是", "shì", "is", "adalah"],
    ["一株小草，", "yì zhū xiǎo cǎo", "a weed", "sepohon rumput kecil"],
    ["如果它", "rú guǒ tā", "if it", "sekiranya ia"],
    ["内心知道", "nèi xīn zhī dào", "inside heart knows", "dalam hati tahu"],
    ["自己是", "zì jǐ shì", "itself is", "dirinya adalah"],
    ["一株百合，", "yì zhū bǎi hé", "a lily", "sepohon bunga lili"],
    ["它也会", "tā yě huì", "it also will", "ia juga akan"],
    ["努力地", "nǔ lì dì", "diligently", "dengan gigih"],
    ["开出", "kāi chū", "bloom", "mengeluarkan"],
    ["美丽的花朵的。", "měi lì de huā duǒ de", "beautiful flowers", "bunga yang cantik."],
    ["这就是", "zhè jiù shì", "this is", "inilah"],
    ["心田上的", "xīn tián shàng de", "in the field of heart", "di dalam lubuk hati punya"],
    ["百合花开。", "bǎi hé huā kāi", "lily blooming", "mekarnya bunga lili."],
    ["\n", "", "", ""],

    // --- 作者落款 ---
    ["（林清玄《心田上的百合花开》，有改动）", "", "", ""]
];
